---
- name: Install Nginx
  apt: 
    name: 
        - nginx
    state: present

- name: Ensure that the default site is removed
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Ensure htpasswd credentials are configured
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: algorand
    password: 'test'

- name: Create the Nginx configuration file
  template: src=app.conf dest=/etc/nginx/conf.d
  notify: Reload Nginx

- name: Ensure Nginx service is started, enable service on restart
  service: name=nginx state=restarted enabled=yes
  when: enabled

# needs to notify handler to come after the restart handlers
- name: Stop nginx
  service: name=nginx state=stopped enabled=no
  notify: Stop Nginx
  when: not enabled
